### ISSUE TITLE
[error] public modifier for extensions with protocol conformances

### ISSUE THREAD

**Issue by oparinov** [rexmas/RealmCrust#1]
Hi,

When I follow the installations steps and copy 

'public extension RealmAdaptor : Adaptor { }'

to my project source, I get the error "Public modifier cannot be used with extensions that declare protocol conformances".

Am I doing something wrong?

Thanks.

**Comment by rexmas** [comment]
Hey @oparinov thank you for pointing this out. It seems that I have documented this incorrectly, I'll update the documentation shortly.

For an example of how things should be implemented look in the tests [here](https://github.com/rexmas/RealmCrust/blob/master/RealmCrustTests/RealmMappingTest.swift#L14)

`Adaptor` already has `public` as its access level, so any extension that inherits it will also have `public` access. Such as explained in the [documentation](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/AccessControl.html#//apple_ref/doc/uid/TP40014097-CH41-ID25).

> Adding Protocol Conformance with an Extension
> 
> You cannot provide an explicit access level modifier for an extension if you are using that extension to add protocol conformance. Instead, the protocol’s own access level is used to provide the default access level for each protocol requirement implementation within the extension.

Just remove `public` and everything should be A'OK. Let me know if you have any more questions!

**Comment by rexmas** [comment]
And please confirm if it worked so we may close the issue :)

**Comment by oparinov** [comment]
Hi @rexmas  thanks for the help!

Now I'm having troubles trying to set up mapping.

When I try to map a property using external mapping like this:

```
tomap.chapter                    <- .Mapping("chapter", chapterMapping) >*<
```

I'm getting this error:

"Type of expression is ambiguous without more context"

Here is the code:

```
import Foundation
import RealmSwift
import Crust
import RealmCrust

class Fact: Object {
    dynamic var uuid: Int = 0
    dynamic var textInDanish = ""
    dynamic var textInEnglish = ""
    dynamic var chapter: Chapter?

}

extension Fact: Mappable { }

class FactMapping : RealmMapping {

    var adaptor: RealmAdaptor
    var primaryKeys: Array<CRMappingKey> {
        return [ "uuid" ]
    }

    required init(adaptor: RealmAdaptor) {
        self.adaptor = adaptor
    }

    func mapping(inout tomap: Fact, context: MappingContext) {
        let chapterMapping = ChapterMapping(adaptor: self.adaptor)

        tomap.chapter                    <- .Mapping("chapter", chapterMapping) >*<
        tomap.uuid                       <- "uuid" >*<
        tomap.textInDanish               <- "textInDanish" >*<
        tomap.textInEnglish              <- "textInEnglish" >*<
        context
    }
}
```

**Comment by rexmas** [comment]
If this is an error thrown by the IDE before building, just try building and it may sort itself out (this is an issue with the compiler I've seen happen before).

Occasionally, if you have another symbol in your Module/App that has the same name of a symbol from another module you're trying to use, you'll need to provide more context to the compiler to know which of the two types you're referring to.

`.Mapping` is a member of `KeyExtensions`. So give `KeyExtensions.Mapping` a try and build again, this should provide enough context to the compiler to infer the correct type.

**Comment by rexmas** [comment]
Did this solve your problem?

**Comment by rexmas** [comment]
No response in over a week, closing.
